version: 2
jobs:
  build:
    branches:
      only:
        - gh-pages
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: git fetch --all
      - run: git branch
      - run: git status
      - run: git remote add mirror https://gitee.com/dayjs/dayjs.git
      - run: git push --all mirror -f
notify:
  webhooks:
    - url: https://hook.bearychat.com/=bw9Gj/circleci/69ef21d626d508766394cd8ce705d6fe
