version: 2
jobs:
  build:
    branches:
      only:
        - gh-pages
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo 2
notify:
  webhooks:
    - url: https://hook.bearychat.com/=bw9Gj/circleci/69ef21d626d508766394cd8ce705d6fe
