version: 2
jobs:
  build:
    branches:
      only:
        - gh-pages
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: git fetch --all
      - run: git remote add mirror git@gitee.com:dayjs/dayjs.git
      - run: git push --all mirror -f
